name: "Flash Particle Device Action"
description: "Flash compiled firmware to a device"
author: "Particle, Inc."
inputs:
  particle-access-token:
    required: true
    description: "Particle API access token with permission to flash devices"
  device-id:
    required: true
    description: "Device ID of the device to be targeted"
  firmware-path:
    required: true
    description: "Path to firmware binary"
  timeout-ms:
    required: false
    default: "600000"
    description: "Time in ms to wait for the device to come back online after flashing"
runs:
  using: "node20"
  main: "dist/index.js"
